trigger:
- main

pool:
  vmImage: ubuntu-latest

name: 1.0.$(Build.BuildId)

jobs:
- job: Build
  displayName: Build the solution
  steps:
  - task: DotNetCoreCLI@2
    displayName: dotnet restore
    inputs:
      command: 'restore'
      projects: '**/*.csproj'
      feedsToUse: 'select'
      vstsFeed: 'd1699579-772c-479f-8d22-bc1c1264e4e3/5873eaff-435b-406e-8f83-9e0546e4ac56'

  - task: DotNetCoreCLI@2
    displayName: dotnet build
    inputs:
      command: 'build'
      projects: '**/*.csproj'

  - task: DotNetCoreCLI@2
    displayName: dotnet test
    inputs:
      command: 'test'
      projects: '**/*.csproj'
      arguments: '--no-build --verbosity normal'

  - task: PublishBuildArtifacts@1
    displayName: Publish build output
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      publishLocation: 'Container'

- job: CreateNugetPackage
  displayName: Create nuget package
  dependsOn: Build
  condition: succeeded()
  steps:
  - task: DownloadBuildArtifacts@0
    displayName: Download build artifacts
    inputs:
      artifactName: 'drop'
      downloadPath: '$(Build.ArtifactStagingDirectory)'

  - task: DotNetCoreCLI@2
    displayName: dotnet pack
    inputs:
      command: 'pack'
      packagesToPack: '**/APICore.csproj'
      versioningScheme: 'byBuildNumber'
      configuration: 'Release'
      outputDirectory: '$(Build.ArtifactStagingDirectory)'

  - task: NuGetAuthenticate@1
    displayName: Authenticate with NuGet
    inputs:
      nuGetServiceConnections: 'MyNugetRestoreConnection'

  - task: DotNetCoreCLI@2
    displayName: dotnet push
    inputs:
      command: 'push'
      packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
      nuGetFeedType: 'internal'
      feedPublish: 'APICoreFeed'

  - task: PublishBuildArtifacts@1
    displayName: Publish NuGet package
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      publishLocation: 'Container'
