trigger:
- main

pool:
  vmImage: ubuntu-latest
name: 1.0.$(Build.BuildId)

jobs:
- job: Build
  displayName: Build the solution
  steps:   
  - task: NuGetAuthenticate@1
    displayName: Authenticate with NuGet  
  - task: DotNetCoreCLI@2
    displayName: dotnet restore
    inputs:
      command: 'restore'
      projects: '**/*.csproj'
      feedsToUse: 'select'
      vstsFeed: 'test-organisation12/APICoreFeed'
     
  - task: DotNetCoreCLI@2
    displayName: dotnet build
    inputs:
      command: 'build'
      projects: '**/*.csproj'

- job: CreateNugetPackage
  displayName: Create NuGet Package
  dependsOn: Build
  condition: succeeded()
  steps:
  - task: DotNetCoreCLI@2
    displayName: dotnet pack
    inputs:
      command: 'pack'
      packagesToPack: '**/APICore.csproj'
      versioningScheme: 'byBuildNumber'
      configuration: 'Release'

  - task: DotNetCoreCLI@2
    displayName: dotnet push
    inputs:
      command: 'push'
      packagesToPush: '$(Build.ArtifactStagingDirectory)/*.nupkg'
      nuGetFeedType: 'internal'
      feedPublish: 'test-organisation12/APICoreFeed'
      verbosityRestore: 'Detailed'

  - task: PublishBuildArtifacts@1
    displayName: Publish Artifact
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'     
      publishLocation: 'Container'
